export { default as IMG01 } from './01.jpg'
export { default as IMG02 } from './02.webp'
export { default as IMG03 } from './03.jpeg'
export { default as IMG04 } from './04.jpeg'
export { default as IMG05 } from './05.jpeg'
export { default as IMG06 } from './06.jpeg'
export { default as IMG07 } from './07.jpeg'

export { default as IMG08 } from './s-01.jpg'
export { default as IMG09 } from './s-02.jpeg'
export { default as IMG10 } from './s-03.jpeg'
export { default as IMG11 } from './s-04.jpeg'
export { default as IMG12 } from './s-05.jpeg'
export { default as IMG13 } from './s-06.jpeg'
