export { default as Header } from './Header'
export { default as Footer } from './Footer'
export { default as Hero } from './Hero'
export { default as Services } from './Services'
export { default as ListMedecines } from './ListMedecines'
export { default as ListBrands } from './ListBrands'
export { default as ListPopularMedecines } from './ListPopularMedecines'
export { default as ListDiscount } from './ListDiscount'
export { default as ListBabyFood } from './ListBabyFood'
export { default as TodayProduct } from './TodayProduct'
export { default as Reviews } from './Reviews'
export { default as ListProducts } from './ListProducts'
export { default as SingleCard } from './SingleCard'
export { default as FAQ } from './FAQ'
export { default as ListSearchedMedecine } from './ListSearchedMedecine'
export { default as FormFilter } from './FormFilter'
export { default as SortMenu } from './SortMenu'

